services:
  db:
    image: mariadb:latest
    container_name: short_url_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: short_url_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short_url_web
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: short_url_nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

volumes:
  db_data: